# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170109_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='article_type',
        ),
    ]
