# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20170113_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleType',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='category',
        ),
    ]
