# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeflow', '0002_auto_20170321_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrecord',
            name='extra_parties',
            field=models.ManyToManyField(blank=True, related_name='related_parties', to=settings.AUTH_USER_MODEL, verbose_name='额外审批人列表'),
        ),
    ]
