# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beeflow', '0004_flow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrecord',
            name='flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beeflow.Flow'),
        ),
    ]
