# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_article_article_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='article_type_id',
        ),
    ]
