# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admininfo',
            options={'verbose_name_plural': '管理员表'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name_plural': '资产表'},
        ),
        migrations.AlterModelOptions(
            name='assetrecord',
            options={'verbose_name_plural': '资产记录表'},
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name_plural': '业务线表'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'verbose_name_plural': '硬盘表'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'verbose_name_plural': '错误日志表'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name_plural': '机房表'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': '内存表'},
        ),
        migrations.AlterModelOptions(
            name='nic',
            options={'verbose_name_plural': '网卡表'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': '服务器表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name_plural': '用户组表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='nic',
            name='up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='repository.UserGroup', verbose_name='业务联系人'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m', to='repository.UserGroup', verbose_name='系统管理员'),
        ),
    ]
