# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170223_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nic',
            old_name='hwaddr',
            new_name='hwaddrs',
        ),
    ]
