# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170223_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nic',
            old_name='hwaddrs',
            new_name='hwaddr',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='ipaddr',
            new_name='ipaddrs',
        ),
    ]
