# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170223_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='content',
            field=models.TextField(),
        ),
    ]
