package com.taotao.cloud.sys.biz.springboot.domain;

import java.io.Serializable;

/**
 * Model class of cnweather1.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Cnweather implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** date_str. */
	private String dateStr;
	
	private String startDate;
	private String endDate;

	/** max_temp. */
	private Double maxTemp;

	/** min_temp. */
	private Double minTemp;

	/** weather_str. */
	private String weatherStr;

	/** wind_direct. */
	private String windDirect;

	/** wind_power. */
	private String windPower;

	/** city. */
	private String city;

	/** city_name. */
	private String cityName;

	/** city_upper. */
	private String cityUpper;

	/** city_code. */
	private String cityCode;

	/**
	 * Constructor.
	 */
	public Cnweather() {
	}

	/**
	 * Set the date_str.
	 * 
	 * @param dateStr
	 *            date_str
	 */
	public void setDateStr(String dateStr) {
		this.dateStr = dateStr;
	}

	/**
	 * Get the date_str.
	 * 
	 * @return date_str
	 */
	public String getDateStr() {
		return this.dateStr;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * Set the max_temp.
	 * 
	 * @param maxTemp
	 *            max_temp
	 */
	public void setMaxTemp(Double maxTemp) {
		this.maxTemp = maxTemp;
	}

	/**
	 * Get the max_temp.
	 * 
	 * @return max_temp
	 */
	public Double getMaxTemp() {
		return this.maxTemp;
	}

	/**
	 * Set the min_temp.
	 * 
	 * @param minTemp
	 *            min_temp
	 */
	public void setMinTemp(Double minTemp) {
		this.minTemp = minTemp;
	}

	/**
	 * Get the min_temp.
	 * 
	 * @return min_temp
	 */
	public Double getMinTemp() {
		return this.minTemp;
	}

	/**
	 * Set the weather_str.
	 * 
	 * @param weatherStr
	 *            weather_str
	 */
	public void setWeatherStr(String weatherStr) {
		this.weatherStr = weatherStr;
	}

	/**
	 * Get the weather_str.
	 * 
	 * @return weather_str
	 */
	public String getWeatherStr() {
		return this.weatherStr;
	}

	/**
	 * Set the wind_direct.
	 * 
	 * @param windDirect
	 *            wind_direct
	 */
	public void setWindDirect(String windDirect) {
		this.windDirect = windDirect;
	}

	/**
	 * Get the wind_direct.
	 * 
	 * @return wind_direct
	 */
	public String getWindDirect() {
		return this.windDirect;
	}

	/**
	 * Set the wind_power.
	 * 
	 * @param windPower
	 *            wind_power
	 */
	public void setWindPower(String windPower) {
		this.windPower = windPower;
	}

	/**
	 * Get the wind_power.
	 * 
	 * @return wind_power
	 */
	public String getWindPower() {
		return this.windPower;
	}

	/**
	 * Set the city.
	 * 
	 * @param city
	 *            city
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * Get the city.
	 * 
	 * @return city
	 */
	public String getCity() {
		return this.city;
	}

	/**
	 * Set the city_name.
	 * 
	 * @param cityName
	 *            city_name
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**
	 * Get the city_name.
	 * 
	 * @return city_name
	 */
	public String getCityName() {
		return this.cityName;
	}

	/**
	 * Set the city_upper.
	 * 
	 * @param cityUpper
	 *            city_upper
	 */
	public void setCityUpper(String cityUpper) {
		this.cityUpper = cityUpper;
	}

	/**
	 * Get the city_upper.
	 * 
	 * @return city_upper
	 */
	public String getCityUpper() {
		return this.cityUpper;
	}

	/**
	 * Set the city_code.
	 * 
	 * @param cityCode
	 *            city_code
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * Get the city_code.
	 * 
	 * @return city_code
	 */
	public String getCityCode() {
		return this.cityCode;
	}


}
