# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以允许屎正文搞自己'),)},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
