server:
  port: 33334
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true
    threads:
      io: 16
      worker: 256
    accesslog:
      dir: ${user.home}/logs/undertow
      enabled: true
  servlet:
    application-display-name: ${spring.application.name}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: taotao-cloud-warehouse-datageneration
  sleuth:
    enabled: true
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.218.3:3306/${spring.application.name}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowMultiQueries=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bigdata
    password: bigdata
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      validation-timeout: 3000
      max-lifetime: 50000
      read-only: false
      connection-test-query: SELECT 1
      maximum-pool-size: 15
      minimum-idle: 10
      pool-name: DatebookHikariCP
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
  kafka:
    bootstrap-servers: 192.168.218.3:9092
    topic: ods_log_full
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0
      properties:
        linger.ms: 100
    consumer:
      auto-commit-interval: 1S
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      missing-topics-fatal: false

generator:
  batch-size: 100  # 每批生成的数据量
  interval: 5000   # 生成数据的时间间隔（毫秒）

# 数据生成配置
generation:
  # 初始数据生成配置
  initial:
    batch-size: 100
    # 用户数据生成配置
    user:
      count: 1000
    # 商品数据生成配置
    product:
      count: 100
      sku-count: 1000
    # 订单数据生成配置
    order:
      count: 1000
      detail-count: 5000
    # 活动数据生成配置
    activity:
      count: 50
      sku-count: 200
    # 优惠券数据生成配置
    coupon:
      count: 100
      user-count: 5000
    # CMS数据生成配置
    cms:
      banner-count: 10
      subject-count: 20
      subject-comment-count: 1000

  # 持续数据生成配置
  continuous:
    enabled: true
    interval: 10  # 生成间隔（秒）
    batch-size: 50
    # 用户行为数据生成配置
    user-behavior:
      enabled: true
      count: 100
    # 订单数据生成配置
    order:
      enabled: true
      count: 50
    # 支付数据生成配置
    payment:
      enabled: true
      count: 50
    # 退款数据生成配置
    refund:
      enabled: true
      count: 10
    # 评价数据生成配置
    comment:
      enabled: true
      count: 100
    # 收藏数据生成配置
    favorite:
      enabled: true
      count: 50
    # 购物车数据生成配置
    cart:
      enabled: true
      count: 100
    # 优惠券使用数据生成配置
    coupon-use:
      enabled: true
      count: 50

taotao:
  boot:
    prometheus:
      enabled: true
    core:
      enabled: true
      env: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
    env:
      post:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: off
    org.springframework.security: off
    org.springframework.security.oauth2: off
    org.springframework.boot.autoconfigure: off
