// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: causa/cgrpc.proto

package com.taotao.cloud.job.common.remote.api;

public final class CausaGrpcClientGen {
  private CausaGrpcClientGen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021causa/cgrpc.proto\032!causa/server_discov" +
      "er_causa.proto\032\032causa/schedule_causa.pro" +
      "to\032\030causa/common_causa.proto\032\033google/pro" +
      "tobuf/empty.proto\032\032causa/register_causa." +
      "proto\032\024causa/mq_causa.proto2\265\001\n\016ServerDi" +
      "scover\022\"\n\tassertApp\022\010.AppName\032\t.Response" +
      "\"\000\022.\n\016heartbeatCheck\022\017.HeartbeatCheck\032\t." +
      "Response\"\000\022 \n\npingServer\022\005.Ping\032\t.Respon" +
      "se\"\000\022-\n\014serverChange\022\020.ServerChangeReq\032\t" +
      ".Response\"\0002{\n\010Schedule\0226\n\025reportWorkerH",
      "eartbeat\022\020.WorkerHeartbeat\032\t.Response\"\000\022" +
      "7\n\021serverScheduleJob\022\025.ServerScheduleJob" +
      "Req\032\t.Response\"\0002\277\001\n\024RegisterToNameServe" +
      "r\0226\n\016serverRegister\022\027.ServerRegisterRepo" +
      "rter\032\t.Response\"\000\0223\n\017workerSubscribe\022\023.W" +
      "orkerSubscribeReq\032\t.Response\"\000\022:\n\017fetchS" +
      "erverList\022\032.FetchServerAddressListReq\032\t." +
      "Response\"\0002L\n\002Mq\022\035\n\004send\022\010.Message\032\t.Res" +
      "ponse\"\000\022\'\n\tcreateJob\022\r.CreateJobReq\032\t.Re" +
      "sponse\"\000B)\n\023com.taotao.cloud.remote.apiB\022CausaGr",
      "pcClientGenb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.taotao.cloud.remote.protos.ServerDiscoverCausa.getDescriptor(),
          com.taotao.cloud.remote.protos.ScheduleCausa.getDescriptor(),
          com.taotao.cloud.remote.protos.CommonCausa.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.taotao.cloud.remote.protos.RegisterCausa.getDescriptor(),
          com.taotao.cloud.remote.protos.MqCausa.getDescriptor(),
        }, assigner);
    com.taotao.cloud.remote.protos.ServerDiscoverCausa.getDescriptor();
    com.taotao.cloud.remote.protos.ScheduleCausa.getDescriptor();
    com.taotao.cloud.remote.protos.CommonCausa.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.taotao.cloud.remote.protos.RegisterCausa.getDescriptor();
    com.taotao.cloud.remote.protos.MqCausa.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
