# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlayermenu',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='菜单排序'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='菜单排序'),
        ),
    ]
