# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_classlist_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='total_class_nums',
            field=models.PositiveIntegerField(default=10, verbose_name='课程总节次'),
        ),
    ]
