# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_classlist_total_class_nums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('web_access_dashboard', '可以访问 每个表的数据列表页'), ('crm_table_index', '可以访问 kingadmin 首页')), 'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
