// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.taotao.cloud.netty.proto;

public interface StreamResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.StreamResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response_info = 1;</code>
     */
    String getResponseInfo();

    /**
     * <code>string response_info = 1;</code>
     */
    com.google.protobuf.ByteString
    getResponseInfoBytes();
}
