// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.taotao.cloud.netty.proto;

public interface StudentResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.StudentResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();

    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>string city = 3;</code>
     */
    String getCity();

    /**
     * <code>string city = 3;</code>
     */
    com.google.protobuf.ByteString
    getCityBytes();
}
