# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=16)),
                ('summary', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, '下线'), (2, '上线')], default=1, verbose_name='状态'),
        ),
    ]
