# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170328_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name_plural': '图片'},
        ),
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(max_length=32, upload_to='', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='img',
            name='summary',
            field=models.CharField(max_length=128, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(max_length=16, verbose_name='标题'),
        ),
    ]
