export interface ISongAction {
  type: SongActionType,
  payload?: any
}

export enum SongActionType {
  // 获取歌曲详情
  GETSONGDETAIL = 'GETSONGDETAIL',
  // 获取歌单详情
  GETPLAYLISTDETAIL = 'GETPLAYLISTDETAIL',
  // 获取推荐歌单
  GETRECOMMENDPLAYLIST = 'GETRECOMMENDPLAYLIST',
  // 获取推荐电台
  GETRECOMMENDDJ = 'GETRECOMMENDDJ',
  // 获取推荐新音乐
  GETRECOMMENDNEWSONG = 'GETRECOMMENDNEWSONG',
  // 获取推荐精彩节目
  GETRECOMMEND = 'GETRECOMMEND',
  // 获取歌曲详情
  GETSONGINFO = 'GETSONGINFO',
  // 切换播放模式
  CHANGEPLAYMODE = 'CHANGEPLAYMODE',
  // 喜欢或者取消喜欢音乐
  LIKEMUSIC = 'LIKEMUSIC',
  // 获取喜欢列表
  GETLIKEMUSICLIST = 'GETLIKEMUSICLIST',
  // 更新获取喜欢列表
  UPDATELIKEMUSICLIST = 'UPDATELIKEMUSICLIST',
  // 更新播放状态
  UPDATEPLAYSTATUS = 'UPDATEPLAYSTATUS',
  // 更新可播放列表
  UPDATECANPLAYLIST = 'UPDATECANPLAYLIST',
  // 更新最近播放tab
  UPDATERECENTTAB = 'UPDATERECENTTAB',
  // 重置播放列表
  RESETPLAYLIST = 'RESETPLAYLIST',
}
