apiVersion: v1
kind: ConfigMap
metadata:
  name: taotao-cloud-open-platform-configmap
data:
  APPLICATION_NAME: "taotao-cloud-open-platform"
  APPLICATION_VERSION: '2025.11'
---
apiVersion: v1
kind: Secret
metadata:
  name: taotao-cloud-open-platform-secret
type: Opaque
data:
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: MTIzNDU2
  TAOTAO_CLOUD_MAIL_PASSWORD: dndkcm1zdm1ldm9zYmVlZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-open-platform
  labels:
    app: taotao-cloud-open-platform
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taotao-cloud-open-platform
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: taotao-cloud-open-platform
    spec:
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: { }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ops-nginx-api
      volumes:
        - name: taotao-cloud-open-platform-hostpath
          hostPath:
            path: /tmp/logs/taotao-cloud-open-platform
            type: Directory
        - name: taotao-cloud-open-platform-secret
          secret:
            secretName: taotao-cloud-open-platform-secret
      containers:
        - name: taotao-cloud-open-platform
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-open-platform:2025.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: admin-port
              containerPort: 33334
          volumeMounts:
            - name: taotao-cloud-open-platform-hostpath
              mountPath: /root/logs
            - name: taotao-cloud-open-platform-secret
              mountPath: /etc/secret
              readOnly: true
          env:
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-open-platform-configmap
                  key: APPLICATION_NAME
            - name: APPLICATION_VERSION
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-open-platform-configmap
                  key: APPLICATION_VERSION
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-open-platform-secret
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-open-platform-secret
                  key: ADMIN_PASSWORD
            - name: TAOTAO_CLOUD_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-open-platform-secret
                  key: TAOTAO_CLOUD_MAIL_PASSWORD
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 33334
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 33334
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - mkdir -p /root/logs/taotao-cloud-open-platform && touch /root/logs/taotao-cloud-open-platform/jit.compile.log /root/logs/taotao-cloud-open-platform/gc.log
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-open-platform
  labels:
    app: taotao-cloud-open-platform
spec:
  type: NodePort
  selector:
    app: taotao-cloud-open-platform
  ports:
    - name: admin-port
      protocol: TCP
      port: 33334
      targetPort: 33334
      nodePort: 33334
