# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeflow', '0003_auto_20170321_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
