# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_task_tasklogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklogdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'initialized'), (1, 'sucess'), (2, 'failed'), (3, 'timeout')], default=0),
        ),
    ]
