apiVersion: v1
kind: ConfigMap
metadata:
  name: taotao-cloud-goods-configmap
data:
  APPLICATION_NAME: "taotao-cloud-goods"
  APPLICATION_VERSION: '2024.11'
---
apiVersion: v1
kind: Secret
metadata:
  name: taotao-cloud-goods-secret
type: Opaque
data:
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: MTIzNDU2
  TAOTAO_CLOUD_MAIL_PASSWORD: dndkcm1zdm1ldm9zYmVlZA==
  DINGDING_TOKEN_ID: MmY4MWExOGZkMjM1ZmZiZWNjMDA1MTlkNTNiYjgwNTRhN2ZmM2U1MGYzMjg3ZTNlNGM1ZmVmNmU1YzhlMTAxNg==
  DINGDING_SECRET: U0VDMmVjMTQ5YjZlYWFiMjZhMTZiM2Q2Yzc4ODQ1ODQ4MjUxZDA2NjdmYjhhYTI4OGIwZTc5ZDg2NzVlNDYwOGQ4MA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-goods
  labels:
    app: taotao-cloud-goods
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taotao-cloud-goods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: taotao-cloud-goods
    spec:
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: { }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ops-nginx-api
      volumes:
        - name: taotao-cloud-goods-hostpath
          hostPath:
            path: /tmp/logs/taotao-cloud-goods
            type: Directory
        - name: taotao-cloud-goods-secret
          secret:
            secretName: taotao-cloud-goods-secret
      initContainers:
        - name: taotao-cloud-goods-init
          image: yauritux/busybox-curl:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "until curl taotao-cloud-xxljob.default:33335/actuator/health; do echo waiting for admin; sleep 10; done;" ]
      containers:
        - name: taotao-cloud-goods
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-goods:2024.11
          imagePullPolicy: Always
          ports:
            - name: order-port
              containerPort: 33338
          volumeMounts:
            - name: taotao-cloud-goods-hostpath
              mountPath: /root/logs
            - name: taotao-cloud-goods-secret
              mountPath: /etc/secret
              readOnly: true
          env:
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-goods-configmap
                  key: APPLICATION_NAME
            - name: APPLICATION_VERSION
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-goods-configmap
                  key: APPLICATION_VERSION
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-goods-secret
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-goods-secret
                  key: ADMIN_PASSWORD
            - name: DINGDING_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-goods-secret
                  key: DINGDING_TOKEN_ID
            - name: DINGDING_SECRET
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-goods-secret
                  key: DINGDING_SECRET
            - name: TAOTAO_CLOUD_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-goods-secret
                  key: TAOTAO_CLOUD_MAIL_PASSWORD
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 33338
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 33338
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - mkdir -p /root/logs/taotao-cloud-goods && touch /root/logs/taotao-cloud-goods/jit.compile.log /root/logs/taotao-cloud-goods/gc.log
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-goods
  labels:
    app: taotao-cloud-goods
spec:
  type: NodePort
  selector:
    app: taotao-cloud-goods
  ports:
    - name: order-port
      protocol: TCP
      port: 33338
      targetPort: 33338
      nodePort: 33338
