# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20161219_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlayermenu',
            name='arg1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='firstlayermenu',
            name='arg2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='firstlayermenu',
            name='arg3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='firstlayermenu',
            unique_together=set([('url_name', 'arg1', 'arg2', 'arg3')]),
        ),
    ]
