# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20161220_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'related_name'), (1, 'absolute_url')], default=0),
        ),
    ]
