# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='homework_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='homework_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
