# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20170115_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以访问 kingadmin 每个表的数据列表页'), ('crm_table_index', '可以访问 kingadmin 首页'), ('crm_table_list_view', '可以访问 kingadmin 每个表中对象的修改页'), ('crm_table_list_change', '可以修改 kingadmin 每个表中对象'), ('crm_table_list_action', '可以操作 每个表的 action 功能')), 'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
