# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20170321_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='firstlayermenu',
            options={'verbose_name': '第一层菜单', 'verbose_name_plural': '第一层菜单'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': '第二层菜单', 'verbose_name_plural': '第二层菜单'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以访问 kingadmin 每个表的数据列表页'), ('crm_table_index', '可以访问 kingadmin 首页'), ('crm_table_list_view', '可以访问 kingadmin 每个表中对象的修改页'), ('crm_table_list_change', '可以修改 kingadmin 每个表中对象'), ('crm_table_list_action', '可以操作 每个表的 action 功能'), ('crm_can_access_my_clients', '可以访问 自己的 客户列表')), 'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
