# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ArticleType',
        ),
    ]
