# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170110_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article2tag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article'),
        ),
        migrations.AlterField(
            model_name='article2tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([('article', 'tag')]),
        ),
    ]
