###
POST http://localhost:1000/sys/addRobot
Content-Type: application/json

{
  "mapId": "1",
  "name": "22",
  "number": "2",
  "robotId": "1308231973000527874",
  "scenicSpotId": "1",
  "userIds": [
    "1"
  ]
}

<> 2020-09-23T052239.200.json

###
GET http://localhost:9700/user/info/security?username=root

<> 2020-10-19T045320.200.json
<> 2020-10-19T044907.200.json

###
GET http://localhost/user/info

###
GET http://localhost:1100/exportActivity

###
GET http://127.0.0.1:1100/exportActivity

###
GET http://localhost:33338/order/info/aaa

###
GET http://localhost:33338/order/info/11

###
GET http://localhost:33338/order/order/xxxx

###
GET http://localhost:33338/order/order/xxxx?memberId=1&code='1221'

###
POST http://127.0.0.1:33333/api/v2023.03/order/excel/export
Content-Type: application/json

{
  "currentPage": 1,
  "pageSize": 10,
  "sort": "id",
  "order": "acs"
}

###
POST http://localhost:33338/order/page

###
POST http://localhost:33338/order/batch
Content-Type: application/json

{
  "method": "create"
}

###
POST http://localhost:33337/sys/tools/email

###
POST http://localhost:33337/sys/tools/setting/save
