###
POST http://127.0.0.1:1000/sys/addRobot
Content-Type: application/json

{
  "mapId": "1",
  "name": "22",
  "number": "2",
  "robotId": "1308231973000527874",
  "scenicSpotId": "1",
  "userIds": [
    "1"
  ]
}

<> 2020-09-23T052239.200.json

###
GET http://127.0.0.1:9700/user/info/security?username=root

<> 2020-10-19T045320.200.json
<> 2020-10-19T044907.200.json

###
GET http://localhost/user/info

###
GET http://127.0.0.1:1100/exportActivity

###
GET http://127.0.0.1:1100/exportActivity

###
GET http://127.0.0.1:33338/order/info/aaa

###
GET http://127.0.0.1:33338/order/info/11

###
GET http://127.0.0.1:33338/order/order/xxxx

###
GET http://127.0.0.1:33338/order/order/xxxx?memberId=1&code='1221'

###
POST http://127.0.0.1:33333/api/v2025.09/order/excel/export
Content-Type: application/json

{
  "currentPage": 1,
  "pageSize": 10,
  "sort": "id",
  "order": "acs"
}

###
POST http://127.0.0.1:33338/order/page

###
POST http://127.0.0.1:33338/order/batch
Content-Type: application/json

{
  "method": "create"
}

###
POST http://127.0.0.1:33337/sys/tools/email

###
POST http://127.0.0.1:33337/sys/tools/setting/save

###
POST http://127.0.0.1:33333/api/v2025.09/auth/api/test/messages
Authorization: bearer eyJraWQiOiIyZTdjYjRiNC1mZDM5LTRjNjQtOGI2ZS01MDllYzBmMjlmYTMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6WyJjbGllbnQxIiwiY2xpZW50MiJdLCJzY29wZSI6WyJzbGRmbCIsInh4eCJdLCJpc3MiOiJodHRwczovL2Jsb2cudGFvdGFvY2xvdWQudG9wLyIsImV4cCI6MTY4ODU1NDAwNSwiaWF0IjoxNjg4NTM2MDA1fQ.Fy0YuQtzXTNjMhxI6j-EfQfPR4Q8vqxhnw0HAjDTOAm12RStnYUVPgMCpk4H4MqF3rdb3LIQSvFFjD4d_klei7OgRjMmnrgrq1v9L0YBhgs2ixXlgG1CmC6o3_-UzXWQbI9Fs7MD2h0HzhePKViEnfp7W9WdozgEuIm9RVyMJUIfSg19MyhEuJyOhnXjyKqhSsjYh4s4pyD-uprdMkS3DctjKYvm0mO62Ux-3zsWC0tMelkqtA8rqZYvx_rn8TeG8kbWX63Lp1Ojw2avsBSTKrP-PIHFfAeh-XBZiYBD0xEjA4AIhdUfdMgnAX16xDMNCGauOPueynISeREzZTC4-Q
