# 密码模式
###
POST http://localhost:9800/oauth/token?grant_type=password&client_id=backend&client_secret=123456&username=root&password=123456&scope=all

###
POST http://localhost:9800/oauth/login?grant_type=password&client_id=backend&client_secret=123456&username=root&password=123456&scope=all&user_type=backend

<> 2020-10-23T102357.200.json
<> 2020-10-22T095649.200.json

###
POST http://localhost:9800/oauth/check_token?token=dd3093ba-2b62-440f-9b8e-4ff1383ef501


###
POST http://localhost:9800/oauth/token?grant_type=refresh_token&refresh_token=6546d7d9-71fc-435d-bb71-5e00433f2c49&client_id=backend&client_secret=123456&scope=all


###
POST http://localhost:9900/api/v1.0/auth/oauth/token?grant_type=password&client_id=backend&client_secret=123456&username=root&password=123456&scope=all


# 客户端模式
###
POST http://localhost:9800/oauth/token?grant_type=client_credentials&client_id=server&client_secret=123456

###
POST http://localhost:9900/api/v1.0/auth/oauth/token?grant_type=client_credentials&client_id=server&client_secret=123456


# 授权码模式
###
GET http://localhost:9800/oauth/authorize?client_id=third_client_1&client_secret=123456&response_type=code&scope=all


###
GET http://127.0.0.1:33337/oauth2/authorization/gitee
# 回调  GET http://127.0.0.1:33337/login/oauth2/code/gitee?code=3d0035d79d97772c0410b5efc9b2ed7b0ffa63bbe965a97b438e2b1733793d3c&state=9hMgjT0EFbpbSJogHOw8BYeDQX5xmh8hMQe7N1iXAmc%3D


###
GET http://127.0.0.1:33337/oauth2/authorization/github
# 回调  GET http://127.0.0.1:33337/login/oauth2/code/github?code=1ad7eb43032c79fadb8f&state=7X2neWrwO2CCpsfnlM0M6HCNnHupp75RCoW1nihFNHQ%3D

###
GET http://127.0.0.1:33337/oauth2/authorization/ttauth
# 回调  GET http://127.0.0.1:33337/login/oauth2/code/ttauth?code=AP4fEveobx91ix3ByaSg15dqfBEoHmwXm4_ARs0jK5wW1emSoqFD0MSIFYQBBmImNd9AuXRno5oshRJcwRjBEftPMVMlt21M5Ogiox8z8ynkC6GVYlyXj9TEH6zyFIPy&state=UfUgHky7oOnLha37Lr4fmaNUV4hXdeDakVqpMNQ-evs%3D
