GET https://silian-es.cqlyy.com/api/yiqing/prevention
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImFsbCJdLCJzaW5nbGVMb2dpbiI6IjEiLCJleHAiOjE2NTc5MDQ3NDUsImp0aSI6ImIwOTQyMzA2LTM5NjYtNDI1Zi1iYzM5LTlmNDAwNTZmZjgzYSIsImNsaWVudF9pZCI6ImFkbWluIiwidG9rZW4iOiJsb2dpbl90b2tlbl8zMTc2MTQyNzA1MDQyMzkxMDkifQ.S0eFu_gN9Ihc9Ry2Efl91lqF4yTfetUJngY2QWL774AgyfohLHbXI-AsVxxhcTsCswG5iW_Ui4Slk_CWapHtDU_rpzFtzOHS0R4ksB9MndayNV6uJLNKgiqP4qLZcMWGmzyFJh-ycwOfYnSxOXjZ1q4grqT4S73CSvoVAgWvBmKyijAm6Dxt-VegwEdP-XcGU5wJxIq91Nuiwlr7WzO5MLvtly78gc_yL-PyoiENBeFaoIKrpBeKfifC2G1Wn5CbxgxTsEvAI4XfKMBnAt0ztjxVyRsQaYW9L5SdwjqIJKWe0fdvvMBWmq_8tF4HxiTKAOzHEVW4V-qv1DVhLRHoxQ

###


