###
GET http://localhost:33336/oauth2/authorize?client_id=authorization-code-messaging-client&client_secret=secret2&response_type=code&redirect_uri=http://127.0.0.1:8080/springauthserverclient/authorized

###

POST http://localhost:33336/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=qAqEK1RedsFMje7yD8SPA7XNT1FcPrQHy0x3gfsW2OSHf1_2xd2QvY3xnTIxDU93uhFNTLMErSJinRYKs32s2anMSUzPDV9Igdiodre4jwM1h8ns3pvIR8o7r7TbEsP1&redirect_uri=http://127.0.0.1:8080/springauthserverclient/authorized

###
POST http://localhost:33336/oauth2/token
Content-Type:  application/x-www-form-urlencoded

grant_type=password&client_id=password-messaging-client&client_secret=secret3&username=admin&password=123456788888

###
POST http://localhost:33336/oauth2/token
Content-Type:  application/x-www-form-urlencoded

grant_type=mobile&client_id=password-messaging-client&client_secret=secret3&mobile=admin&verification_code=123456788888



#################################
###
GET http://localhost:33336/messages

### authorization_code 认证第一步
GET http://localhost:33336/oauth2/authorize?client_id=authorization-code-messaging-client&client_secret=secret2&response_type=code&redirect_uri=http://127.0.0.1:8080/springauthserverclient/authorized

###
### authorization_code 认证第二步
POST http://localhost:33336/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=authorization-code-messaging-client&client_secret=secret2&redirect_uri=http://127.0.0.1:8080/springauthserverclient/authorized&code=aHFaI96h8f7L7Rukt69DFBilnXDopp2bA2DvRm77-AWFybwqqKQiB-bdZkB0OFtWWNtxyCdU7MmnR_1OUP8_8yV5Kc9zQdLWGUCPDpDgl3HiyAzPVGmsR2cWGZIkPMC3

###

### 自定义client-credential认证示例
POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=client&client_secret=123456

###

### 自定义 password 认证示例
POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=client&client_secret=123456&username=admin&password=123456

###

### 自定义 refresh_token 认证示例
POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=client&client_secret=123456&refresh_token=H-MfxBSKWLk5YJT1HbP6mnBmEa2z13N2QL913jJRyBPuOD99CbRFsHXxRgCwUUvjd8XlRL8i8ElZjZMpBd_lFq5O5H-SqGwunkqv6T-Jq1LGVNXZ54m2qN3po36d1RGP

###
GET http://localhost:33336/messages




###
GET http://localhost:33336/oauth2/authorize?client_id=e4da4a32-592b-46f0-ae1d-784310e88423&client_secret=secret&response_type=code&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/gatewayclient

