# 不带字体
# docker tag isahl/openjdk17:amd64 registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:amd64

FROM registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:amd64

USER root

RUN mkdir /skywalking

COPY ./skywalking-agent /skywalking/agent

#docker build -t registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-skywalking:8.8.1 .



# jre17 带字体
# docker tag sunrdocker/jdk17-jre-font-openssl-alpine:latest registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:jre-font
# docker push registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:jre-font

FROM registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:jre-font

USER root

#wget https://dlcdn.apache.org/skywalking/java-agent/8.12.0/apache-skywalking-java-agent-8.12.0.tgz
RUN mkdir /skywalking
#wget https://github.com/pyroscope-io/pyroscope-java/releases/download/v0.10.2/pyroscope.jar
RUN mkdir /pyroscope

COPY ./skywalking-agent /skywalking/agent
COPY ./pyroscope-agent /pyroscope/agent

# docker build -t registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:skywalking8.12.0-pyroscope0.10.2-jre-font .
# docker push registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-openjdk17:skywalking8.12.0-pyroscope0.10.2-jre-font

