apiVersion: v1
kind: ConfigMap
metadata:
  name: taotao-cloud-manager-configmap
data:
  APPLICATION_NAME: "taotao-cloud-manager"
  APPLICATION_VERSION: '2025.11'
---
apiVersion: v1
kind: Secret
metadata:
  name: taotao-cloud-manager-secret
type: Opaque
data:
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: MTIzNDU2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-manager
  labels:
    app: taotao-cloud-manager
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taotao-cloud-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: taotao-cloud-manager
    spec:
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: { }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ops-nginx-api
      volumes:
        - name: taotao-cloud-manager-hostpath
          hostPath:
            path: /tmp/logs/taotao-cloud-manager
            type: Directory
        - name: taotao-cloud-manager-secret
          secret:
            secretName: taotao-cloud-manager-secret
      containers:
        - name: taotao-cloud-manager
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-manager:2025.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: manager-port
              containerPort: 44446
          volumeMounts:
            - name: taotao-cloud-manager-hostpath
              mountPath: /usr/local/openresty/nginx/logs
            - name: taotao-cloud-manager-secret
              mountPath: /etc/secret
              readOnly: true
          env:
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-manager-configmap
                  key: APPLICATION_NAME
            - name: APPLICATION_VERSION
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-manager-configmap
                  key: APPLICATION_VERSION
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-manager-secret
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-manager-secret
                  key: ADMIN_PASSWORD
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2048Mi
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - ls -l
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-manager
  labels:
    app: taotao-cloud-manager
spec:
  type: NodePort
  selector:
    app: taotao-cloud-manager
  ports:
    - name: manager-port
      protocol: TCP
      port: 44446
      targetPort: 44446
      nodePort: 44446
