# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_column='user', db_index=True, max_length=32, null=True),
        ),
    ]
