# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170320_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Part')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
