# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170320_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateField()),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='par',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.AddField(
            model_name='usertotag',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
