# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20170320_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertotag',
            unique_together=set([('u', 't')]),
        ),
    ]
