apiVersion: v1
kind: ConfigMap
metadata:
  name: taotao-cloud-customer-configmap
data:
  APPLICATION_NAME: "taotao-cloud-customer"
  APPLICATION_VERSION: '2025.11'
---
apiVersion: v1
kind: Secret
metadata:
  name: taotao-cloud-customer-secret
type: Opaque
data:
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: MTIzNDU2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-customer
  labels:
    app: taotao-cloud-customer
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taotao-cloud-customer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: taotao-cloud-customer
    spec:
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: { }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ops-nginx-api
      volumes:
        - name: taotao-cloud-customer-hostpath
          hostPath:
            path: /tmp/logs/taotao-cloud-customer
            type: Directory
        - name: taotao-cloud-customer-secret
          secret:
            secretName: taotao-cloud-customer-secret
      containers:
        - name: taotao-cloud-customer
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-customer:2025.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: oauth2-port
              containerPort: 33402
          volumeMounts:
            - name: taotao-cloud-customer-hostpath
              mountPath: /root/logs
            - name: taotao-cloud-customer-secret
              mountPath: /etc/secret
              readOnly: true
          env:
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-customer-configmap
                  key: APPLICATION_NAME
            - name: APPLICATION_VERSION
              valueFrom:
                configMapKeyRef:
                  name: taotao-cloud-customer-configmap
                  key: APPLICATION_VERSION
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-customer-secret
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taotao-cloud-customer-secret
                  key: ADMIN_PASSWORD
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 33402
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 33402
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - mkdir -p /root/logs/taotao-cloud-customer && touch /root/logs/taotao-cloud-customer/jit.compile.log /root/logs/taotao-cloud-customer/gc.log
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-customer
  labels:
    app: taotao-cloud-customer
spec:
  type: NodePort
  selector:
    app: taotao-cloud-customer
  ports:
    - name: oauth2-port
      protocol: TCP
      port: 33402
      targetPort: 33402
      nodePort: 33402
