// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.taotao.cloud.netty.proto;

/**
 * Protobuf type {@code  MyResponse}
 */
public final class MyResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements: MyResponse)
        MyResponseOrBuilder {
    // Use MyResponse.newBuilder() to construct.
    private MyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private MyResponse() {
        realname_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private MyResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        realname_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return  StudentProto.internal_static_com_shengsiyuan_proto_MyResponse_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return  StudentProto.internal_static_com_shengsiyuan_proto_MyResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                         MyResponse.class,  MyResponse.Builder.class);
    }

    public static final int REALNAME_FIELD_NUMBER = 2;
    private volatile Object realname_;

    /**
     * <code>string realname = 2;</code>
     */
    @Override
	public String getRealname() {
        Object ref = realname_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            realname_ = s;
            return s;
        }
    }

    /**
     * <code>string realname = 2;</code>
     */
    @Override
	public com.google.protobuf.ByteString
    getRealnameBytes() {
        Object ref = realname_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            realname_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
	public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
			return true;
		}
        if (isInitialized == 0) {
			return false;
		}

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getRealnameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, realname_);
        }
    }

    @Override
	public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
			return size;
		}

        size = 0;
        if (!getRealnameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, realname_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof  MyResponse)) {
            return super.equals(obj);
        }
         MyResponse other = ( MyResponse) obj;

        boolean result = true;
        result = result && getRealname()
                .equals(other.getRealname());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REALNAME_FIELD_NUMBER;
        hash = (53 * hash) + getRealname().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static  MyResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static  MyResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static  MyResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static  MyResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static  MyResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static  MyResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static  MyResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static  MyResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static  MyResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static  MyResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
	public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder( MyResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
	public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code  MyResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements: MyResponse)
             MyResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return  StudentProto.internal_static_com_shengsiyuan_proto_MyResponse_descriptor;
        }

        @Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return  StudentProto.internal_static_com_shengsiyuan_proto_MyResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                             MyResponse.class,  MyResponse.Builder.class);
        }

        // Construct using  MyResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
		public Builder clear() {
            super.clear();
            realname_ = "";

            return this;
        }

        @Override
		public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return  StudentProto.internal_static_com_shengsiyuan_proto_MyResponse_descriptor;
        }

        @Override
		public  MyResponse getDefaultInstanceForType() {
            return  MyResponse.getDefaultInstance();
        }

        @Override
		public  MyResponse build() {
             MyResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
		public  MyResponse buildPartial() {
             MyResponse result = new  MyResponse(this);
            result.realname_ = realname_;
            onBuilt();
            return result;
        }

        @Override
		public Builder clone() {
            return (Builder) super.clone();
        }

        @Override
		public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        @Override
		public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        @Override
		public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        @Override
		public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        @Override
		public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        @Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof  MyResponse) {
                return mergeFrom(( MyResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom( MyResponse other) {
            if (other ==  MyResponse.getDefaultInstance()) {
				return this;
			}
            if (!other.getRealname().isEmpty()) {
                realname_ = other.realname_;
                onChanged();
            }
            onChanged();
            return this;
        }

        @Override
		public final boolean isInitialized() {
            return true;
        }

        @Override
		public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
             MyResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = ( MyResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object realname_ = "";

        /**
         * <code>string realname = 2;</code>
         */
        @Override
		public String getRealname() {
            Object ref = realname_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                realname_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string realname = 2;</code>
         */
        @Override
		public com.google.protobuf.ByteString
        getRealnameBytes() {
            Object ref = realname_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                realname_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string realname = 2;</code>
         */
        public Builder setRealname(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            realname_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string realname = 2;</code>
         */
        public Builder clearRealname() {

            realname_ = getDefaultInstance().getRealname();
            onChanged();
            return this;
        }

        /**
         * <code>string realname = 2;</code>
         */
        public Builder setRealnameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            realname_ = value;
            onChanged();
            return this;
        }

        @Override
		public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        @Override
		public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope: MyResponse)
    }

    // @@protoc_insertion_point(class_scope: MyResponse)
    private static final  MyResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new  MyResponse();
    }

    public static  MyResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyResponse>
            PARSER = new com.google.protobuf.AbstractParser<MyResponse>() {
        @Override
		public MyResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new MyResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<MyResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyResponse> getParserForType() {
        return PARSER;
    }

    @Override
	public  MyResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

