// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.taotao.cloud.netty.proto;

/**
 * Protobuf type {@code  StreamRequest}
 */
public final class StreamRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements: StreamRequest)
        StreamRequestOrBuilder {
    // Use StreamRequest.newBuilder() to construct.
    private StreamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private StreamRequest() {
        requestInfo_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private StreamRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        requestInfo_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return  StudentProto.internal_static_com_shengsiyuan_proto_StreamRequest_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return  StudentProto.internal_static_com_shengsiyuan_proto_StreamRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                         StreamRequest.class,  StreamRequest.Builder.class);
    }

    public static final int REQUEST_INFO_FIELD_NUMBER = 1;
    private volatile Object requestInfo_;

    /**
     * <code>string request_info = 1;</code>
     */
    @Override
	public String getRequestInfo() {
        Object ref = requestInfo_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            requestInfo_ = s;
            return s;
        }
    }

    /**
     * <code>string request_info = 1;</code>
     */
    @Override
	public com.google.protobuf.ByteString
    getRequestInfoBytes() {
        Object ref = requestInfo_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            requestInfo_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
	public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
			return true;
		}
        if (isInitialized == 0) {
			return false;
		}

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getRequestInfoBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestInfo_);
        }
    }

    @Override
	public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
			return size;
		}

        size = 0;
        if (!getRequestInfoBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestInfo_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof  StreamRequest)) {
            return super.equals(obj);
        }
         StreamRequest other = ( StreamRequest) obj;

        boolean result = true;
        result = result && getRequestInfo()
                .equals(other.getRequestInfo());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REQUEST_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getRequestInfo().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static  StreamRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static  StreamRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static  StreamRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static  StreamRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static  StreamRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static  StreamRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static  StreamRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static  StreamRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static  StreamRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static  StreamRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
	public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder( StreamRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
	public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code  StreamRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements: StreamRequest)
             StreamRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return  StudentProto.internal_static_com_shengsiyuan_proto_StreamRequest_descriptor;
        }

        @Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return  StudentProto.internal_static_com_shengsiyuan_proto_StreamRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                             StreamRequest.class,  StreamRequest.Builder.class);
        }

        // Construct using  StreamRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
		public Builder clear() {
            super.clear();
            requestInfo_ = "";

            return this;
        }

        @Override
		public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return  StudentProto.internal_static_com_shengsiyuan_proto_StreamRequest_descriptor;
        }

        @Override
		public  StreamRequest getDefaultInstanceForType() {
            return  StreamRequest.getDefaultInstance();
        }

        @Override
		public  StreamRequest build() {
             StreamRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
		public  StreamRequest buildPartial() {
             StreamRequest result = new  StreamRequest(this);
            result.requestInfo_ = requestInfo_;
            onBuilt();
            return result;
        }

        @Override
		public Builder clone() {
            return (Builder) super.clone();
        }

        @Override
		public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        @Override
		public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        @Override
		public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        @Override
		public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        @Override
		public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        @Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof  StreamRequest) {
                return mergeFrom(( StreamRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom( StreamRequest other) {
            if (other ==  StreamRequest.getDefaultInstance()) {
				return this;
			}
            if (!other.getRequestInfo().isEmpty()) {
                requestInfo_ = other.requestInfo_;
                onChanged();
            }
            onChanged();
            return this;
        }

        @Override
		public final boolean isInitialized() {
            return true;
        }

        @Override
		public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
             StreamRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = ( StreamRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object requestInfo_ = "";

        /**
         * <code>string request_info = 1;</code>
         */
        @Override
		public String getRequestInfo() {
            Object ref = requestInfo_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                requestInfo_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string request_info = 1;</code>
         */
        @Override
		public com.google.protobuf.ByteString
        getRequestInfoBytes() {
            Object ref = requestInfo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                requestInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string request_info = 1;</code>
         */
        public Builder setRequestInfo(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            requestInfo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string request_info = 1;</code>
         */
        public Builder clearRequestInfo() {

            requestInfo_ = getDefaultInstance().getRequestInfo();
            onChanged();
            return this;
        }

        /**
         * <code>string request_info = 1;</code>
         */
        public Builder setRequestInfoBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            requestInfo_ = value;
            onChanged();
            return this;
        }

        @Override
		public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        @Override
		public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope: StreamRequest)
    }

    // @@protoc_insertion_point(class_scope: StreamRequest)
    private static final  StreamRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new  StreamRequest();
    }

    public static  StreamRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamRequest>
            PARSER = new com.google.protobuf.AbstractParser<StreamRequest>() {
        @Override
		public StreamRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new StreamRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<StreamRequest> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StreamRequest> getParserForType() {
        return PARSER;
    }

    @Override
	public  StreamRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

