// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.taotao.cloud.netty.proto;

public interface StudentResponseListOrBuilder extends
        // @@protoc_insertion_point(interface_extends: StudentResponseList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated . StudentResponse studentResponse = 1;</code>
     */
    java.util.List< StudentResponse>
    getStudentResponseList();

    /**
     * <code>repeated . StudentResponse studentResponse = 1;</code>
     */
     StudentResponse getStudentResponse(int index);

    /**
     * <code>repeated . StudentResponse studentResponse = 1;</code>
     */
    int getStudentResponseCount();

    /**
     * <code>repeated . StudentResponse studentResponse = 1;</code>
     */
    java.util.List<? extends  StudentResponseOrBuilder>
    getStudentResponseOrBuilderList();

    /**
     * <code>repeated . StudentResponse studentResponse = 1;</code>
     */
     StudentResponseOrBuilder getStudentResponseOrBuilder(int index);
}
