# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'URL表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='user2role',
            options={'verbose_name_plural': '用户分配角色'},
        ),
        migrations.AddField(
            model_name='permission',
            name='caption',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
