# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20170410_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': '操作表'},
        ),
        migrations.AddField(
            model_name='action',
            name='code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
