# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170328_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='video',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='video',
            name='level',
        ),
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(max_length=32, upload_to='static/upload', verbose_name='图片路径'),
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
