# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='alex', max_length=32),
            preserve_default=False,
        ),
    ]
