### 原始接口
GET http://192.168.218.1:33331/buyer/sys/dict/query/type?type=333

### 网关接口
GET http://192.168.218.1:33305/api/v2026.04/sys/buyer/sys/dict/query/type?type=333



### 原始接口
GET http://192.168.218.1:33331/sys/mall/dict/testMybatisQueryStructure

### 网关接口
GET http://192.168.218.1:33305/api/v2026.04/sys/mall/dict/testMybatisQueryStructure
